language: ruby
os:
- linux
- osx
rvm:
- 2.5
before_install:
- nvm install 8
- npm install -g puppeteer
- gem install metanorma-cli
script:
- |
  for template in advisory collection directive report standard; do
    metanorma new test/$template --type csd --doctype $template --template . --overwrite
    metanorma compile $PWD/test/$template/document.adoc
  done