
[[terms]]
== Terms, definitions and abbreviations

=== Terms and definitions

==== calendar spam

calendar events and meeting invitations containing term:[spam] delivered
through term:[calendar systems,calendar system]


==== calendar abuse

malicious usage of a term:[calendar system],
possibly leading to an term:[attack]
on the receiving user


==== spam

unsolicited or unwanted information


==== attack

attempt to destroy, expose, alter, disable, steal or gain unauthorized
access to or make unauthorized use of an asset

[.source]
<<ISO27000>>


==== calendar system

information system that provides calendar and scheduling functionality for user
accounts


==== mail system

information system that provides electronic mail functionality


==== user system

information system that provides authentication and authorization functionality


=== Abbreviations

iMIP:: iCalendar Message-Based Interoperability Protocol (see <<iMIP>>)
iTIP:: iCalendar Transport-Independent Interoperability Protocol (see <<iTIP>>)
SMTP:: Simple Mail Transfer Protocol (see <<SMTP>>)
DNSBL:: Domain Name System-based Blackhole List
URIBL:: Realtime URI Blacklist
ARF:: Abuse Reporting Format
