= CalConnect Template: Admin

This repository contains the CalConnect Admin document template.

This document is available in its rendered forms here:

* https://github-account.github.io/my-repo-name/[Metanorma HTML]
* https://github-account.github.io/my-repo-name/my-repo-name.pdf[PDF]
* https://github-account.github.io/my-repo-name/my-repo-name.xml[Metanorma XML]
* https://github-account.github.io/my-repo-name/my-repo-name.rxl[Relaton XML (Bibliographic item)]

Because of all this, there is no need to build the document on your own, but if you wish to do so, this is how it can be done:

== Fetching the document

[source,sh]
----
git clone https://github.com/travis-account/my-repo-name/
----

== Installing Build Tools

See https://www.metanorma.com/overview/getting-started/


== Running via Docker or locally

If you have installed the build tools locally, and wish to run the
locally-installed compilation tools, there is nothing further to set.

If you don't want to deal with local dependencies, use the docker
version by:

[source,sh]
----
export METANORMA_DOCKER=1
----

The `Makefile` will automatically choose the proper command to
execute.


== Building The Document

[source,sh]
----
make clean all
----

The following outputs will be built:

* CSD XML (https://github.com/metanorma/metanorma-model-csd) (`[filename].xml`)
* HTML (`[filename].html`)
* PDF (`[filename].pdf`)
* Word DOC (`[filename].doc`)


== Iterating the document

[source,sh]
----
make html
open csd-*.html
----
